name: GitHub Actions

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      # Install Node
      - name: Setup Node
        uses: actions/setup-node@v4

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Lint
      - name: Run ESLint
        run: npm run lint

      # Type check
      - name: Run TypeScript check
        run: npm run typecheck

      # Test
      - name: Run Tests
        run: npm run test
